//#define BETA_VERSION

#define PRODUCT_NAME L"Recent Items Exclusions"
#define PRODUCT_VERSION L"0.0.0.1"
#define RAW_FILE_VERSION 0,0,0,1
#define RAW_PRODUCT_VERSION 0,0,0,1
#define RESOURCE_FILE_VERSION RAW_PRODUCT_VERSION
#define RESOURCE_PRODUCT_VERSION PRODUCT_VERSION
#define RESOURCE_LEGAL_COPYRIGHT "(c)2023 Bitsum LLC"
#define RESOURCE_COMPANY_NAME "Bitsum LLC"

// for internet requests
#define PRODUCT_USER_AGENT PRODUCT_NAME L"/" PRODUCT_VERSION

#pragma once
